language: python

matrix:
  include:
    - python: 3.7
      dist: xenial

services:
  - docker

install:
  - pip install -r requirements.txt
  - pip install -r dev-dependencies.txt

before_script:
  # - docker build --build-arg GIT_TAG=5a16373a3c535f77304709f725e10284dccfbea1 -t aergo/node ./docker
  - docker-compose -f ./docker/docker-compose.yml up&
  - docker_pid=$!
  - sleep 20

  - make deploy_bridge
  - make deploy_token

  - make validator&
  - validator_pid=$!

  - make proposer&
  - proposer_pid=$!

  - make broadcaster&
  - broadcaster_pid=$!

script:
  - make tests

after_script: 
  - kill $broadcaster_pid
  - kill $proposer_pid
  - kill $validator_pid
  - kill $docker_pid
  - make clean