language: python

matrix:
  include:
    - python: 3.7
      dist: xenial

services:
  - docker

install:
  - pip install -r requirements.txt
  - pip install -r dev-dependencies.txt

before_script:
  # - docker build --build-arg GIT_TAG=3f24ea32ddeb27dd1b86671d1622ab2108a1f42e -t aergo/node ./docker
  - docker-compose -f ./docker/docker-compose.yml up&
  - docker_pid=$!
  - sleep 20

  - make deploy_test_bridge

  - make validator&
  - validator_pid=$!

  - make proposer&
  - proposer_pid=$!

script:
  - make tests

after_script: 
  - kill $proposer_pid
  - kill $validator_pid
  - kill $docker_pid
  - make clean