# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aergo_bridge_operator/bridge_operator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='aergo_bridge_operator/bridge_operator.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n+aergo_bridge_operator/bridge_operator.proto\"Z\n\x06\x41nchor\x12\x17\n\x0fis_from_mainnet\x18\x01 \x01(\x08\x12\x0c\n\x04root\x18\x02 \x01(\t\x12\x0e\n\x06height\x18\x03 \x01(\t\x12\x19\n\x11\x64\x65stination_nonce\x18\x04 \x01(\t\"7\n\x08\x41pproval\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0b\n\x03sig\x18\x02 \x01(\x0c\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"M\n\x08NewTempo\x12\x17\n\x0fis_from_mainnet\x18\x01 \x01(\x08\x12\r\n\x05tempo\x18\x02 \x01(\x04\x12\x19\n\x11\x64\x65stination_nonce\x18\x03 \x01(\x04\"W\n\rNewValidators\x12\x17\n\x0fis_from_mainnet\x18\x01 \x01(\x08\x12\x12\n\nvalidators\x18\x02 \x03(\t\x12\x19\n\x11\x64\x65stination_nonce\x18\x03 \x01(\x04\x32\xd0\x01\n\x0e\x42ridgeOperator\x12*\n\x12GetAnchorSignature\x12\x07.Anchor\x1a\t.Approval\"\x00\x12-\n\x13GetTAnchorSignature\x12\t.NewTempo\x1a\t.Approval\"\x00\x12,\n\x12GetTFinalSignature\x12\t.NewTempo\x1a\t.Approval\"\x00\x12\x35\n\x16GetValidatorsSignature\x12\x0e.NewValidators\x1a\t.Approval\"\x00\x62\x06proto3')
)




_ANCHOR = _descriptor.Descriptor(
  name='Anchor',
  full_name='Anchor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_from_mainnet', full_name='Anchor.is_from_mainnet', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='root', full_name='Anchor.root', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='Anchor.height', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='destination_nonce', full_name='Anchor.destination_nonce', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=137,
)


_APPROVAL = _descriptor.Descriptor(
  name='Approval',
  full_name='Approval',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='Approval.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sig', full_name='Approval.sig', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='Approval.error', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=194,
)


_NEWTEMPO = _descriptor.Descriptor(
  name='NewTempo',
  full_name='NewTempo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_from_mainnet', full_name='NewTempo.is_from_mainnet', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tempo', full_name='NewTempo.tempo', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='destination_nonce', full_name='NewTempo.destination_nonce', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=273,
)


_NEWVALIDATORS = _descriptor.Descriptor(
  name='NewValidators',
  full_name='NewValidators',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_from_mainnet', full_name='NewValidators.is_from_mainnet', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='validators', full_name='NewValidators.validators', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='destination_nonce', full_name='NewValidators.destination_nonce', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=275,
  serialized_end=362,
)

DESCRIPTOR.message_types_by_name['Anchor'] = _ANCHOR
DESCRIPTOR.message_types_by_name['Approval'] = _APPROVAL
DESCRIPTOR.message_types_by_name['NewTempo'] = _NEWTEMPO
DESCRIPTOR.message_types_by_name['NewValidators'] = _NEWVALIDATORS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Anchor = _reflection.GeneratedProtocolMessageType('Anchor', (_message.Message,), {
  'DESCRIPTOR' : _ANCHOR,
  '__module__' : 'aergo_bridge_operator.bridge_operator_pb2'
  # @@protoc_insertion_point(class_scope:Anchor)
  })
_sym_db.RegisterMessage(Anchor)

Approval = _reflection.GeneratedProtocolMessageType('Approval', (_message.Message,), {
  'DESCRIPTOR' : _APPROVAL,
  '__module__' : 'aergo_bridge_operator.bridge_operator_pb2'
  # @@protoc_insertion_point(class_scope:Approval)
  })
_sym_db.RegisterMessage(Approval)

NewTempo = _reflection.GeneratedProtocolMessageType('NewTempo', (_message.Message,), {
  'DESCRIPTOR' : _NEWTEMPO,
  '__module__' : 'aergo_bridge_operator.bridge_operator_pb2'
  # @@protoc_insertion_point(class_scope:NewTempo)
  })
_sym_db.RegisterMessage(NewTempo)

NewValidators = _reflection.GeneratedProtocolMessageType('NewValidators', (_message.Message,), {
  'DESCRIPTOR' : _NEWVALIDATORS,
  '__module__' : 'aergo_bridge_operator.bridge_operator_pb2'
  # @@protoc_insertion_point(class_scope:NewValidators)
  })
_sym_db.RegisterMessage(NewValidators)



_BRIDGEOPERATOR = _descriptor.ServiceDescriptor(
  name='BridgeOperator',
  full_name='BridgeOperator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=365,
  serialized_end=573,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetAnchorSignature',
    full_name='BridgeOperator.GetAnchorSignature',
    index=0,
    containing_service=None,
    input_type=_ANCHOR,
    output_type=_APPROVAL,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetTAnchorSignature',
    full_name='BridgeOperator.GetTAnchorSignature',
    index=1,
    containing_service=None,
    input_type=_NEWTEMPO,
    output_type=_APPROVAL,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetTFinalSignature',
    full_name='BridgeOperator.GetTFinalSignature',
    index=2,
    containing_service=None,
    input_type=_NEWTEMPO,
    output_type=_APPROVAL,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetValidatorsSignature',
    full_name='BridgeOperator.GetValidatorsSignature',
    index=3,
    containing_service=None,
    input_type=_NEWVALIDATORS,
    output_type=_APPROVAL,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BRIDGEOPERATOR)

DESCRIPTOR.services_by_name['BridgeOperator'] = _BRIDGEOPERATOR

# @@protoc_insertion_point(module_scope)
