# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from aergo_bridge_operator import bridge_operator_pb2 as aergo__bridge__operator_dot_bridge__operator__pb2


class BridgeOperatorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetAnchorSignature = channel.unary_unary(
        '/BridgeOperator/GetAnchorSignature',
        request_serializer=aergo__bridge__operator_dot_bridge__operator__pb2.Anchor.SerializeToString,
        response_deserializer=aergo__bridge__operator_dot_bridge__operator__pb2.Approval.FromString,
        )
    self.GetTAnchorSignature = channel.unary_unary(
        '/BridgeOperator/GetTAnchorSignature',
        request_serializer=aergo__bridge__operator_dot_bridge__operator__pb2.NewTempo.SerializeToString,
        response_deserializer=aergo__bridge__operator_dot_bridge__operator__pb2.Approval.FromString,
        )
    self.GetTFinalSignature = channel.unary_unary(
        '/BridgeOperator/GetTFinalSignature',
        request_serializer=aergo__bridge__operator_dot_bridge__operator__pb2.NewTempo.SerializeToString,
        response_deserializer=aergo__bridge__operator_dot_bridge__operator__pb2.Approval.FromString,
        )
    self.GetValidatorsSignature = channel.unary_unary(
        '/BridgeOperator/GetValidatorsSignature',
        request_serializer=aergo__bridge__operator_dot_bridge__operator__pb2.NewValidators.SerializeToString,
        response_deserializer=aergo__bridge__operator_dot_bridge__operator__pb2.Approval.FromString,
        )
    self.GetOracleSignature = channel.unary_unary(
        '/BridgeOperator/GetOracleSignature',
        request_serializer=aergo__bridge__operator_dot_bridge__operator__pb2.NewOracle.SerializeToString,
        response_deserializer=aergo__bridge__operator_dot_bridge__operator__pb2.Approval.FromString,
        )


class BridgeOperatorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetAnchorSignature(self, request, context):
    """Get signatures of anchoring messages on aergo1 and aergo2
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTAnchorSignature(self, request, context):
    """Get signature to update anchoring periode
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTFinalSignature(self, request, context):
    """Get signature to update finality
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetValidatorsSignature(self, request, context):
    """Get signature to update validators of anchors
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetOracleSignature(self, request, context):
    """Get signature to update bridge oracle
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BridgeOperatorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetAnchorSignature': grpc.unary_unary_rpc_method_handler(
          servicer.GetAnchorSignature,
          request_deserializer=aergo__bridge__operator_dot_bridge__operator__pb2.Anchor.FromString,
          response_serializer=aergo__bridge__operator_dot_bridge__operator__pb2.Approval.SerializeToString,
      ),
      'GetTAnchorSignature': grpc.unary_unary_rpc_method_handler(
          servicer.GetTAnchorSignature,
          request_deserializer=aergo__bridge__operator_dot_bridge__operator__pb2.NewTempo.FromString,
          response_serializer=aergo__bridge__operator_dot_bridge__operator__pb2.Approval.SerializeToString,
      ),
      'GetTFinalSignature': grpc.unary_unary_rpc_method_handler(
          servicer.GetTFinalSignature,
          request_deserializer=aergo__bridge__operator_dot_bridge__operator__pb2.NewTempo.FromString,
          response_serializer=aergo__bridge__operator_dot_bridge__operator__pb2.Approval.SerializeToString,
      ),
      'GetValidatorsSignature': grpc.unary_unary_rpc_method_handler(
          servicer.GetValidatorsSignature,
          request_deserializer=aergo__bridge__operator_dot_bridge__operator__pb2.NewValidators.FromString,
          response_serializer=aergo__bridge__operator_dot_bridge__operator__pb2.Approval.SerializeToString,
      ),
      'GetOracleSignature': grpc.unary_unary_rpc_method_handler(
          servicer.GetOracleSignature,
          request_deserializer=aergo__bridge__operator_dot_bridge__operator__pb2.NewOracle.FromString,
          response_serializer=aergo__bridge__operator_dot_bridge__operator__pb2.Approval.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'BridgeOperator', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
