# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: broadcaster/broadcaster.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='broadcaster/broadcaster.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1d\x62roadcaster/broadcaster.proto\"\xa9\x01\n\x0eSignedTransfer\x12\r\n\x05owner\x18\x01 \x01(\t\x12\x12\n\ntoken_name\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\t\x12\r\n\x05nonce\x18\x04 \x01(\x04\x12\x11\n\tsignature\x18\x05 \x01(\t\x12\x0b\n\x03\x66\x65\x65\x18\x06 \x01(\t\x12\x10\n\x08\x64\x65\x61\x64line\x18\x07 \x01(\x04\x12\x11\n\tis_pegged\x18\x08 \x01(\x08\x12\x10\n\x08receiver\x18\t \x01(\t\"m\n\x0f\x45xecutionStatus\x12\x17\n\x0f\x64\x65posit_tx_hash\x18\x01 \x01(\t\x12\x18\n\x10withdraw_tx_hash\x18\x02 \x01(\t\x12\x18\n\x10transfer_tx_hash\x18\x03 \x01(\t\x12\r\n\x05\x65rror\x18\x04 \x01(\t2{\n\x0b\x42roadcaster\x12\x35\n\x0e\x42ridgeTransfer\x12\x0f.SignedTransfer\x1a\x10.ExecutionStatus\"\x00\x12\x35\n\x0eSimpleTransfer\x12\x0f.SignedTransfer\x1a\x10.ExecutionStatus\"\x00\x62\x06proto3')
)




_SIGNEDTRANSFER = _descriptor.Descriptor(
  name='SignedTransfer',
  full_name='SignedTransfer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='owner', full_name='SignedTransfer.owner', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='token_name', full_name='SignedTransfer.token_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='SignedTransfer.amount', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nonce', full_name='SignedTransfer.nonce', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signature', full_name='SignedTransfer.signature', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fee', full_name='SignedTransfer.fee', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deadline', full_name='SignedTransfer.deadline', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_pegged', full_name='SignedTransfer.is_pegged', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='receiver', full_name='SignedTransfer.receiver', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=203,
)


_EXECUTIONSTATUS = _descriptor.Descriptor(
  name='ExecutionStatus',
  full_name='ExecutionStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='deposit_tx_hash', full_name='ExecutionStatus.deposit_tx_hash', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='withdraw_tx_hash', full_name='ExecutionStatus.withdraw_tx_hash', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='transfer_tx_hash', full_name='ExecutionStatus.transfer_tx_hash', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='ExecutionStatus.error', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=205,
  serialized_end=314,
)

DESCRIPTOR.message_types_by_name['SignedTransfer'] = _SIGNEDTRANSFER
DESCRIPTOR.message_types_by_name['ExecutionStatus'] = _EXECUTIONSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SignedTransfer = _reflection.GeneratedProtocolMessageType('SignedTransfer', (_message.Message,), dict(
  DESCRIPTOR = _SIGNEDTRANSFER,
  __module__ = 'broadcaster.broadcaster_pb2'
  # @@protoc_insertion_point(class_scope:SignedTransfer)
  ))
_sym_db.RegisterMessage(SignedTransfer)

ExecutionStatus = _reflection.GeneratedProtocolMessageType('ExecutionStatus', (_message.Message,), dict(
  DESCRIPTOR = _EXECUTIONSTATUS,
  __module__ = 'broadcaster.broadcaster_pb2'
  # @@protoc_insertion_point(class_scope:ExecutionStatus)
  ))
_sym_db.RegisterMessage(ExecutionStatus)



_BROADCASTER = _descriptor.ServiceDescriptor(
  name='Broadcaster',
  full_name='Broadcaster',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=316,
  serialized_end=439,
  methods=[
  _descriptor.MethodDescriptor(
    name='BridgeTransfer',
    full_name='Broadcaster.BridgeTransfer',
    index=0,
    containing_service=None,
    input_type=_SIGNEDTRANSFER,
    output_type=_EXECUTIONSTATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SimpleTransfer',
    full_name='Broadcaster.SimpleTransfer',
    index=1,
    containing_service=None,
    input_type=_SIGNEDTRANSFER,
    output_type=_EXECUTIONSTATUS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BROADCASTER)

DESCRIPTOR.services_by_name['Broadcaster'] = _BROADCASTER

# @@protoc_insertion_point(module_scope)
