# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from broadcaster import broadcaster_pb2 as broadcaster_dot_broadcaster__pb2


class BroadcasterStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.BridgeTransfer = channel.unary_unary(
        '/Broadcaster/BridgeTransfer',
        request_serializer=broadcaster_dot_broadcaster__pb2.SignedTransfer.SerializeToString,
        response_deserializer=broadcaster_dot_broadcaster__pb2.ExecutionStatus.FromString,
        )
    self.SimpleTransfer = channel.unary_unary(
        '/Broadcaster/SimpleTransfer',
        request_serializer=broadcaster_dot_broadcaster__pb2.SignedTransfer.SerializeToString,
        response_deserializer=broadcaster_dot_broadcaster__pb2.ExecutionStatus.FromString,
        )


class BroadcasterServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def BridgeTransfer(self, request, context):
    """Request execution of a signed transfer
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SimpleTransfer(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BroadcasterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'BridgeTransfer': grpc.unary_unary_rpc_method_handler(
          servicer.BridgeTransfer,
          request_deserializer=broadcaster_dot_broadcaster__pb2.SignedTransfer.FromString,
          response_serializer=broadcaster_dot_broadcaster__pb2.ExecutionStatus.SerializeToString,
      ),
      'SimpleTransfer': grpc.unary_unary_rpc_method_handler(
          servicer.SimpleTransfer,
          request_deserializer=broadcaster_dot_broadcaster__pb2.SignedTransfer.FromString,
          response_serializer=broadcaster_dot_broadcaster__pb2.ExecutionStatus.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Broadcaster', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
