# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bridge_operator/bridge_operator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bridge_operator/bridge_operator.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n%bridge_operator/bridge_operator.proto\"Z\n\x06\x41nchor\x12\x17\n\x0fis_from_mainnet\x18\x01 \x01(\x08\x12\x0c\n\x04root\x18\x02 \x01(\t\x12\x0e\n\x06height\x18\x03 \x01(\t\x12\x19\n\x11\x64\x65stination_nonce\x18\x04 \x01(\t\"7\n\x08\x41pproval\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0b\n\x03sig\x18\x02 \x01(\x0c\x12\r\n\x05\x65rror\x18\x03 \x01(\t2<\n\x0e\x42ridgeOperator\x12*\n\x12GetAnchorSignature\x12\x07.Anchor\x1a\t.Approval\"\x00\x62\x06proto3')
)




_ANCHOR = _descriptor.Descriptor(
  name='Anchor',
  full_name='Anchor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_from_mainnet', full_name='Anchor.is_from_mainnet', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='root', full_name='Anchor.root', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='Anchor.height', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='destination_nonce', full_name='Anchor.destination_nonce', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=131,
)


_APPROVAL = _descriptor.Descriptor(
  name='Approval',
  full_name='Approval',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='Approval.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sig', full_name='Approval.sig', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='Approval.error', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=188,
)

DESCRIPTOR.message_types_by_name['Anchor'] = _ANCHOR
DESCRIPTOR.message_types_by_name['Approval'] = _APPROVAL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Anchor = _reflection.GeneratedProtocolMessageType('Anchor', (_message.Message,), dict(
  DESCRIPTOR = _ANCHOR,
  __module__ = 'bridge_operator.bridge_operator_pb2'
  # @@protoc_insertion_point(class_scope:Anchor)
  ))
_sym_db.RegisterMessage(Anchor)

Approval = _reflection.GeneratedProtocolMessageType('Approval', (_message.Message,), dict(
  DESCRIPTOR = _APPROVAL,
  __module__ = 'bridge_operator.bridge_operator_pb2'
  # @@protoc_insertion_point(class_scope:Approval)
  ))
_sym_db.RegisterMessage(Approval)



_BRIDGEOPERATOR = _descriptor.ServiceDescriptor(
  name='BridgeOperator',
  full_name='BridgeOperator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=190,
  serialized_end=250,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetAnchorSignature',
    full_name='BridgeOperator.GetAnchorSignature',
    index=0,
    containing_service=None,
    input_type=_ANCHOR,
    output_type=_APPROVAL,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BRIDGEOPERATOR)

DESCRIPTOR.services_by_name['BridgeOperator'] = _BRIDGEOPERATOR

# @@protoc_insertion_point(module_scope)
