# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bridge_operator/bridge_operator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bridge_operator/bridge_operator.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n%bridge_operator/bridge_operator.proto\"?\n\tProposals\x12\x18\n\x07\x61nchor1\x18\x01 \x01(\x0b\x32\x07.Anchor\x12\x18\n\x07\x61nchor2\x18\x02 \x01(\x0b\x32\x07.Anchor\"A\n\x06\x41nchor\x12\x0c\n\x04root\x18\x01 \x01(\t\x12\x0e\n\x06height\x18\x02 \x01(\t\x12\x19\n\x11\x64\x65stination_nonce\x18\x03 \x01(\t\"8\n\tApprovals\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0c\n\x04sig1\x18\x02 \x01(\x0c\x12\x0c\n\x04sig2\x18\x03 \x01(\x0c\x32@\n\x0e\x42ridgeOperator\x12.\n\x12GetAnchorSignature\x12\n.Proposals\x1a\n.Approvals\"\x00\x62\x06proto3')
)




_PROPOSALS = _descriptor.Descriptor(
  name='Proposals',
  full_name='Proposals',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='anchor1', full_name='Proposals.anchor1', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='anchor2', full_name='Proposals.anchor2', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=104,
)


_ANCHOR = _descriptor.Descriptor(
  name='Anchor',
  full_name='Anchor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='root', full_name='Anchor.root', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='Anchor.height', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='destination_nonce', full_name='Anchor.destination_nonce', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=171,
)


_APPROVALS = _descriptor.Descriptor(
  name='Approvals',
  full_name='Approvals',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='Approvals.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sig1', full_name='Approvals.sig1', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sig2', full_name='Approvals.sig2', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=229,
)

_PROPOSALS.fields_by_name['anchor1'].message_type = _ANCHOR
_PROPOSALS.fields_by_name['anchor2'].message_type = _ANCHOR
DESCRIPTOR.message_types_by_name['Proposals'] = _PROPOSALS
DESCRIPTOR.message_types_by_name['Anchor'] = _ANCHOR
DESCRIPTOR.message_types_by_name['Approvals'] = _APPROVALS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Proposals = _reflection.GeneratedProtocolMessageType('Proposals', (_message.Message,), dict(
  DESCRIPTOR = _PROPOSALS,
  __module__ = 'bridge_operator.bridge_operator_pb2'
  # @@protoc_insertion_point(class_scope:Proposals)
  ))
_sym_db.RegisterMessage(Proposals)

Anchor = _reflection.GeneratedProtocolMessageType('Anchor', (_message.Message,), dict(
  DESCRIPTOR = _ANCHOR,
  __module__ = 'bridge_operator.bridge_operator_pb2'
  # @@protoc_insertion_point(class_scope:Anchor)
  ))
_sym_db.RegisterMessage(Anchor)

Approvals = _reflection.GeneratedProtocolMessageType('Approvals', (_message.Message,), dict(
  DESCRIPTOR = _APPROVALS,
  __module__ = 'bridge_operator.bridge_operator_pb2'
  # @@protoc_insertion_point(class_scope:Approvals)
  ))
_sym_db.RegisterMessage(Approvals)



_BRIDGEOPERATOR = _descriptor.ServiceDescriptor(
  name='BridgeOperator',
  full_name='BridgeOperator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=231,
  serialized_end=295,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetAnchorSignature',
    full_name='BridgeOperator.GetAnchorSignature',
    index=0,
    containing_service=None,
    input_type=_PROPOSALS,
    output_type=_APPROVALS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BRIDGEOPERATOR)

DESCRIPTOR.services_by_name['BridgeOperator'] = _BRIDGEOPERATOR

# @@protoc_insertion_point(module_scope)
